# Disable below since compiled package is downloaded from Nexus
- name: Install Maven
  ansible.builtin.yum:
    name: maven
    state: installed

# Install Java 11 to adjust memory for performance issues
#- name: Install Java
#  ansible.builtin.yum:
#    name: java-11-openjdk
#    state: installed

- name: App Pre-Req
  ansible.builtin.include_tasks: "app-prereq.yml"

# Disable below since compiled package is downloaded from Nexus
- name: Maven Build
  ansible.builtin.shell: mvn clean package ; mv target/{{component}}-1.0.jar {{component}}.jar
  args:
    chdir: /app

- name: SystemD Setup
  ansible.builtin.include_tasks: "systemd.yml"

- name: Load Schema
  ansible.builtin.include_tasks: "{{schema_type}}-schema.yml"
  when: schema_load


